Minor updates to README.md files
PureStorage-OpenConnect/pure-fb-openmetrics-exporter pull request #18
Opened 2023-01-13 18:57 UTC by james-laing

2023-03-07 14:10 UTC, sdodsley requested changes

2023-03-07 15:09 UTC, james-laing commented on extra/grafana/README.md
> +curl -H 'Authorization: Bearer a12345bc6-d78e-901f-23a4-56b07b89012' -X GET 'http://<exporter_ip>:9490/metrics/array?endpoint=arrayname01.fqdn.com'
It's not a real Bearer token. The format is correct the the letters and numbers that make it up are sequential.

2023-04-21 15:00 UTC, sdodsley approved these changes

2023-04-21 15:13 UTC, sdodsley approved these changes

2023-04-21 16:33 UTC, james-laing commented
Fixes issue #22

2023-04-23 16:27 UTC, merged