New release to add the enhancement requested in issue #19
PureStorage-OpenConnect/pure-fb-openmetrics-exporter pull request #23
Opened 2023-04-28 20:28 UTC by genegr

2023-04-28 22:36 UTC, sdodsley requested changes

2023-04-28 22:36 UTC, sdodsley commented on README.md
> +| http://\<exporter-host\>:\<port\>/metrics/polucies | endpoint       | NFS policies info metrics |
typo: policies

2023-04-28 22:36 UTC, sdodsley commented on README.md
> +The first option requires to specify the api-token value as the authorization parameter of the specific job in the Prometheus configuration file.
change `to specify` to `specifying`

2023-04-28 22:36 UTC, sdodsley commented on README.md
> +The second option provides the FlashBlade/api-token key-pair map for a list of arrays in a simple YAML configuration file that is passed as paramether to the exporter. This makes possible to write mo
typo: parameter

2023-04-29 07:03 UTC, genegr commented on README.md
> +The first option requires to specify the api-token value as the authorization parameter of the specific job in the Prometheus configuration file.
Fixed

2023-04-29 07:03 UTC, genegr commented on README.md
> +The second option provides the FlashBlade/api-token key-pair map for a list of arrays in a simple YAML configuration file that is passed as paramether to the exporter. This makes possible to write mo
Fixed

2023-04-29 07:04 UTC, genegr commented on README.md
> +| http://\<exporter-host\>:\<port\>/metrics/polucies | endpoint       | NFS policies info metrics |
Fixed

2023-05-01 17:56 UTC, sdodsley approved these changes

2023-05-01 21:04 UTC, merged